# Generated by Django 6.0.1 on 2026-02-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_studentprofile_remove_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_commission',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ሳይከፈል ያለ'), ('PAID', 'የተከፈለ/ያልተረከበ'), ('COMPLETED', 'የተረከበ/የተጠናቀቀ'), ('CANCELLED', 'ተሰርዟል')], default='PENDING', max_length=20),
        ),
    ]
