# Generated by Django 6.0.1 on 2026-02-02 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0004_cafe_balance_order_admin_commission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='ባለቤቱ ቦቱን ሲጀምር የሚለይበት ID', unique=True)),
                ('access_password', models.CharField(help_text='ባለቤቱ ቦቱ ላይ መጀመሪያ ሲገባ የሚጠየቀው ፓስዎርድ', max_length=50)),
                ('is_locked', models.BooleanField(default=False, help_text='3 ጊዜ ከተሳሳተ ይታገዳል')),
                ('failed_attempts', models.IntegerField(default=0)),
                ('is_authorized', models.BooleanField(default=False, help_text='ዴቨሎፐሩ ፈቃድ ካልሰጠው መስራት አይችልም')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='cafes.cafe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'የካፌ ባለቤት',
                'verbose_name_plural': 'የካፌ ባለቤቶች',
            },
        ),
    ]
