# Generated by Django 6.0.1 on 2026-02-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0005_cafeowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='employee_password',
            field=models.CharField(default='1234', help_text='ሰራተኞች የሚጠቀሙበት ኮድ', max_length=10),
        ),
        migrations.AddField(
            model_name='cafe',
            name='is_open',
            field=models.BooleanField(default=True, help_text='ካፌው ለጊዜው ዝግ ከሆነ False ይደረጋል'),
        ),
        migrations.AddField(
            model_name='cafeowner',
            name='owner_secret_key',
            field=models.CharField(blank=True, help_text='ባለቤቱ ራሱ የሚቀይረው መለያ', max_length=50, null=True),
        ),
    ]
