# Generated by Django 6.0.1 on 2026-02-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0006_cafe_employee_password_cafe_is_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='employee_telegram_id',
            field=models.BigIntegerField(blank=True, help_text='የተፈቀደለት ሰራተኛ የቴሌግራም ID', null=True),
        ),
    ]
