# Generated by Django 6.0.1 on 2026-02-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0007_cafe_employee_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='verified_by_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
