# Generated by Django 6.0.1 on 2026-02-05 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0008_order_verified_by_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='current_stock',
            field=models.IntegerField(default=0, help_text='የቀረው የምግብ መጠን'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_waiting_mode',
            field=models.BooleanField(default=False, help_text='ምግብ አልቆ ሰው እየጠበቀ ከሆነ'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='ባለቤቱ የሚሞላው የምግብ መጠን'),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.menuitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.studentprofile')),
            ],
        ),
    ]
