# Generated by Django 6.0.1 on 2026-02-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0009_menuitem_current_stock_menuitem_is_waiting_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='employee_password',
            field=models.CharField(help_text='የሰራተኛው ፓስዎርድ (Hashed)', max_length=128),
        ),
        migrations.AlterField(
            model_name='cafeowner',
            name='access_password',
            field=models.CharField(help_text='የባለቤቱ ፓስዎርድ (Hashed)', max_length=128),
        ),
    ]
