# Generated by Django 6.0.1 on 2026-02-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0010_alter_cafe_employee_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeowner',
            name='email',
            field=models.EmailField(blank=True, help_text='የባለቤቱ Gmail አድራሻ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='የተጠቃሚው Gmail አድራሻ', max_length=255, null=True),
        ),
    ]
