# Generated by Django 6.0.1 on 2026-02-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0011_cafeowner_email_studentprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeowner',
            name='last_otp_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafeowner',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='cafeowner',
            name='reset_count_today',
            field=models.IntegerField(default=0),
        ),
    ]
