# Generated by Django 6.0.1 on 2026-02-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0012_cafeowner_last_otp_time_cafeowner_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='የተሰረዘበት ሰዓት', null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='ካፌው ከተሰረዘ True ይሆናል (Recycle Bin)'),
        ),
    ]
