# Generated by Django 6.0.1 on 2026-02-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0013_cafe_deleted_at_cafe_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='employee_failed_attempts',
            field=models.IntegerField(default=0, help_text='ሰራተኛው የተሳሳተ ሙከራ ሲያደርግ ይቆጥራል'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='employee_full_name',
            field=models.CharField(blank=True, help_text='የሰራተኛው ሙሉ ስም', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='employee_last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='is_employee_locked',
            field=models.BooleanField(default=False, help_text='ሰራተኛው 3 ጊዜ ከተሳሳተ True ይሆናል'),
        ),
    ]
