# Generated by Django 6.0.1 on 2026-02-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0014_cafe_employee_failed_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='employee_full_name',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='employee_last_login',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='employee_failed_attempts',
            field=models.IntegerField(default=0, help_text='የተሳሳቱ ሙከራዎች ብዛት'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='is_employee_locked',
            field=models.BooleanField(default=False, help_text='ሰራተኛው 3 ጊዜ ከተሳሳተ ይታገዳል'),
        ),
    ]
