# Generated by Django 6.0.1 on 2026-02-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0015_remove_cafe_employee_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_json',
            field=models.TextField(default='{}', help_text='የታዘዙ ምግቦች ዝርዝር በJSON'),
        ),
    ]
